# Generated by Django 4.2.4 on 2023-09-27 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskfact",
            old_name="project",
            new_name="project_fact",
        ),
        migrations.RenameField(
            model_name="taskfact",
            old_name="stage",
            new_name="stage_fact",
        ),
    ]
