# Generated by Django 4.2.4 on 2023-09-26 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_projectplan_project_creation_stage_projectfact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stages", "0006_stagefact"),
        ("tasks", "0002_remove_taskplan_task_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskFact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField()),
                ("task_number", models.IntegerField(blank=True, null=True)),
                ("duration_per_hour", models.IntegerField(default=0.0)),
                ("duration_per_day", models.IntegerField(default=0.0)),
                ("total_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                (
                    "action_status",
                    models.IntegerField(
                        choices=[
                            (1, "План"),
                            (2, "Активный"),
                            (3, "Завершенный"),
                            (4, "Отменено"),
                            (5, "На удерживании"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_task_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="projects.projectfact",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="stages.stagefact"
                    ),
                ),
                (
                    "task_plan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.taskplan"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_task_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт Задача",
                "verbose_name_plural": "Факт Задачы",
            },
        ),
    ]
