# Generated by Django 4.2.4 on 2023-09-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0002_rename_project_taskfact_project_fact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskfact",
            name="project_fact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_fact",
                to="projects.projectfact",
            ),
        ),
    ]
