# Generated by Django 4.2.4 on 2023-09-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0003_alter_taskfact_project_fact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskplan",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_plan_task",
                to="projects.projectplan",
            ),
        ),
    ]
