# Generated by Django 4.2.4 on 2023-09-07 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_alter_projectplan_project_creation_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateField()),
                ("finish_time", models.DateField()),
                ("stage_number", models.IntegerField(blank=True, null=True)),
                ("duration_per_hour", models.IntegerField(default=0.0)),
                ("duration_per_day", models.IntegerField(default=0.0)),
                ("total_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projectPlan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.projectplan"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "План Этап",
                "verbose_name_plural": "План Этапы",
            },
        ),
    ]
