# Generated by Django 4.2.4 on 2023-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageplan",
            name="contributions_to_IT_park",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stageplan",
            name="cost_price",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stageplan",
            name="period_expenses",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stageplan",
            name="salary_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
    ]
