# Generated by Django 4.2.4 on 2023-09-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagefact",
            name="stage_plan",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="stages.stageplan"
            ),
        ),
    ]
