# Generated by Django 4.2.4 on 2023-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0002_stageplan_contributions_to_it_park_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageplan",
            name="total_price_with_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
