# Generated by Django 4.2.4 on 2023-09-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0002_alter_stagefact_stage_plan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stagefact",
            old_name="name",
            new_name="description",
        ),
        migrations.AddField(
            model_name="stagefact",
            name="contributions_to_IT_park",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="cost_price",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="margin",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="period_expenses",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="salary_cost",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="total_price_stage_and_task",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name="stagefact",
            name="total_price_with_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
