# Generated by Django 4.2.4 on 2023-09-27 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0003_rename_name_stagefact_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stagefact",
            old_name="project",
            new_name="project_fact",
        ),
    ]
