# Generated by Django 4.2.4 on 2023-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0003_stageplan_total_price_with_margin"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageplan",
            name="total_price_stage_and_task",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
