# Generated by Django 4.2.4 on 2023-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0004_stageplan_total_price_stage_and_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageplan",
            name="margin",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=1000),
        ),
    ]
