# Generated by Django 4.2.4 on 2023-09-26 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_projectplan_project_creation_stage_projectfact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stages", "0005_stageplan_margin"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageFact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateField()),
                ("finish_time", models.DateField()),
                ("stage_number", models.IntegerField(blank=True, null=True)),
                ("duration_per_hour", models.IntegerField(default=0.0)),
                ("duration_per_day", models.IntegerField(default=0.0)),
                ("total_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_stage_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.projectfact"
                    ),
                ),
                (
                    "stage_plan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.projectplan"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_stage_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт Этап",
                "verbose_name_plural": "Факт Этапы",
            },
        ),
    ]
