# Generated by Django 4.2.4 on 2023-08-31 03:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salary_cost", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("cost_price", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("period_expenses", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("contributions_to_IT_park", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("total_cost", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("file_order", models.FileField(upload_to="uploads/finance/calculation_order/")),
                ("report_month", models.CharField(blank=True, max_length=25, null=True)),
                ("calculation_for_projects", models.BooleanField(default=False)),
                ("percent_salary_cost", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("percent_cost_price", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                ("percent_period_expenses", models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
                (
                    "percent_contributions_to_IT_park",
                    models.DecimalField(decimal_places=10, default=0.0, max_digits=25),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_cost_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_cost_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cтоимость труда в час",
                "verbose_name_plural": "Cтоимость труда в час",
            },
        ),
    ]
