# Generated by Django 4.2.4 on 2023-09-05 12:26

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coefficient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("factors_making_project_difficult", models.TextField(blank=True, max_length=300, null=True)),
                ("coefficient", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coefficient_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coefficient_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Коэффициент, повышающие стоимость проектирования ИС",
                "verbose_name_plural": "Коэффициенты, повышающие стоимость проектирования ИС",
            },
        ),
        migrations.CreateModel(
            name="ProjectPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("customer", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "responsible_subject_for_project",
                    models.IntegerField(
                        choices=[
                            (1, "«Единый интегратор по созданию государственных информационных систем UZINFOCOM»"),
                            (2, "Другой"),
                        ],
                        default=1,
                    ),
                ),
                ("legal_basis", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "source_of_financing",
                    models.IntegerField(
                        choices=[
                            (1, "ФРИКТ"),
                            (2, "Государственное учреждение"),
                            (3, "Частный сектор"),
                            (4, "Другой"),
                        ],
                        default=2,
                    ),
                ),
                ("involved_in_development_country", models.BooleanField(default=True)),
                ("expert_conclusion", models.FileField(upload_to="uploads/expert_conclusion")),
                (
                    "customer_status",
                    models.IntegerField(
                        choices=[
                            (1, "ПРАВООХРАНИТЕЛЬНЫЕ ОРГАНЫ"),
                            (2, "БЛАГОТВОРИТЕЛЬНОСТЬ"),
                            (3, "ГОССЕКТОР"),
                            (4, "АГРОПРОМЫШЛЕННОСТЬ"),
                            (5, "ОБРАЗОВАНИЕ"),
                            (6, "ИНТЕРНЕТ И ИНФОРМАЦИОННЫЕ ТЕХНОЛОГИИ"),
                            (7, "МЕДИЦИНА"),
                            (8, "ФИНАНСОВЫЕ ТЕХНОЛОГИИ"),
                        ],
                        default=3,
                    ),
                ),
                ("purpose", ckeditor.fields.RichTextField()),
                ("objective", ckeditor.fields.RichTextField()),
                ("start_time", models.DateField()),
                ("finish_time", models.DateField()),
                ("expecting_results", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                ("salary_cost", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("cost_price", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("period_expenses", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("contributions_to_IT_park", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("margin", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("total_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("total_price_stage_and_task", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("total_price_with_margin", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                (
                    "total_price_with_additional_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
                ),
                ("additional_cost", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("duration_per_hour", models.IntegerField(default=0.0)),
                ("duration_per_day", models.IntegerField(default=0.0)),
                ("percent_salary_cost", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                ("percent_cost_price", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                (
                    "percent_contributions_to_IT_park",
                    models.DecimalField(decimal_places=20, default=0.0, max_digits=1000),
                ),
                ("percent_margin", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                ("percent_period_expenses", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                (
                    "project_creation_stage",
                    models.IntegerField(
                        choices=[(1, "Этап 1"), (2, "Этап 2"), (3, "Этап 3"), (4, "В подтверждении")], default=1
                    ),
                ),
                (
                    "project_status",
                    models.IntegerField(
                        choices=[
                            (1, "В создании"),
                            (2, "В подтверждении"),
                            (3, "Активный"),
                            (4, "Завершенный"),
                            (5, "Отменено"),
                            (6, "На удерживании"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "project_phase",
                    models.IntegerField(choices=[(1, "План"), (2, "Активный"), (3, "Завершенный")], default=1),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coefficient",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="projects.coefficient"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="users.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "План Проект",
                "verbose_name_plural": "План Проекты",
            },
        ),
    ]
