# Generated by Django 4.2.4 on 2023-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectplan",
            name="project_creation_stage",
            field=models.IntegerField(
                choices=[(1, "Этап 1"), (2, "Паспорт проекта"), (3, "Этап 3"), (4, "Этап 4"), (5, "В подтверждении")],
                default=1,
            ),
        ),
    ]
