# Generated by Django 4.2.4 on 2023-09-26 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_alter_projectplan_project_creation_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectplan",
            name="project_creation_stage",
            field=models.IntegerField(
                choices=[(1, "Этап 1"), (2, "Этап 2"), (3, "Этап 3"), (4, "В подтверждении")], default=1
            ),
        ),
        migrations.CreateModel(
            name="ProjectFact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateField()),
                ("finish_time", models.DateField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                ("salary_cost", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("cost_price", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("period_expenses", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("contributions_to_IT_park", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("margin", models.DecimalField(decimal_places=8, default=0.0, max_digits=1000)),
                ("total_price_stage_and_task", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("total_price_with_margin", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                (
                    "total_price_with_additional_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
                ),
                ("additional_cost", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("duration_per_hour", models.IntegerField(default=0.0)),
                ("duration_per_day", models.IntegerField(default=0.0)),
                ("percent_salary_cost", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                ("percent_cost_price", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                (
                    "percent_contributions_to_IT_park",
                    models.DecimalField(decimal_places=20, default=0.0, max_digits=1000),
                ),
                ("percent_margin", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                ("percent_period_expenses", models.DecimalField(decimal_places=20, default=0.0, max_digits=1000)),
                (
                    "project_status",
                    models.IntegerField(
                        choices=[
                            (1, "В создании"),
                            (2, "В подтверждении"),
                            (3, "Активный"),
                            (4, "Завершенный"),
                            (5, "Отменено"),
                            (6, "На удерживании"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "project_phase",
                    models.IntegerField(choices=[(1, "План"), (2, "Активный"), (3, "Завершенный")], default=2),
                ),
                ("coefficient_of_project", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_fact",
                        to="projects.projectplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт Проект",
                "verbose_name_plural": "Факт Проекты",
            },
        ),
    ]
