# Generated by Django 4.2.4 on 2023-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectfact_profitability_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectplan",
            name="profitability_percentage",
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=1000),
        ),
    ]
