# Generated by Django 4.2.4 on 2023-09-26 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_alter_projectplan_project_creation_stage_projectfact"),
        ("additionalCosts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCostFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cost_type",
                    models.IntegerField(
                        choices=[(1, "Аутсорсинг"), (2, "Оборудование"), (3, "Прочие расходы")], default=3
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500, null=True)),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_fact_additional_cost_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.projectfact"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_fact_additional_cost_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт Доп. расход",
                "verbose_name_plural": "Факт Доп. расходы",
            },
        ),
    ]
